feat: Call LearningAssistantSummary endpoint
edx/frontend-lib-learning-assistant pull request #68
Opened 2024-11-26 19:14 UTC by ilee2u

https://2u-internal.atlassian.net/browse/COSMO-575

2024-11-27 14:04 UTC, varshamenon4 reviewed
Looks good so far! A couple of questions!

2024-12-02 16:02 UTC, ilee2u commented on src/components/Sidebar/index.jsx
> +      {
Following up from a standup discussion we had, I removed the gating here as that functionality will be implemented in another ticket.

2024-12-03 20:31 UTC, ilee2u commented on src/data/api.js
> +  const url = new URL(`${getConfig().CHAT_RESPONSE_URL}/${courseId}/summary`);
NOTE: This Ticket/PR has been modified such that we're now calling the "summary" endpoint that Michael is working on in his PR: https://github.com/edx/learning-assistant/pull/140.

This endpoint gets all the data for `enabled`, `message_history`, and `audit_trial` all in one GET request.

2024-12-03 20:31 UTC, ilee2u commented on src/data/thunks.js
> +export function getLearningAssistantSummary(courseId) {
I replaced the `getLearningAssistantMessageHistory`, `getIsEnabled `, and `getAuditTrial` thunks with a singular `getLearningAssistantSummary` thunk.

2024-12-03 20:31 UTC, ilee2u commented on src/hooks/index.js
Let me know if I need to revert this, but I removed the `message-history` hook because I was able to call the summary hook from Xpert.jsx

2024-12-03 21:48 UTC, varshamenon4 commented on src/components/Sidebar/index.jsx
> +      {
Sounds great!

2024-12-04 14:10 UTC, varshamenon4 reviewed
Looks good! Just a couple of nits/comments.

2024-12-04 14:10 UTC, varshamenon4 commented on src/data/api.test.js
> +    const mockGet = jest.fn(async () => ({
Nice renaming!

2024-12-04 14:10 UTC, varshamenon4 commented on src/data/thunks.js
> +            // NOTE to self: can't store Date() objects in store: https://github.com/reduxjs/redux-toolkit/issues/456
Question: would you just store as a string then and parse when needed?

2024-12-04 14:10 UTC, varshamenon4 commented on src/data/thunks.js
> +            // NOTE to self: can't store Date() objects in store: https://github.com/reduxjs/redux-toolkit/issues/456
Oh wait, that's what you're doing! My bad. So you can probably remove this comment?

2024-12-04 14:10 UTC, varshamenon4 commented on src/widgets/Xpert.jsx
> +  // NOTE: This value can be used later on if/when we pass the enrollment mode to this componentn
nit:
```suggestion
  // NOTE: This value can be used later on if/when we pass the enrollment mode to this component
```

2024-12-04 18:39 UTC, MichaelRoytman requested changes
We shouldn't merge this pull request until the corresponding backend changes are released, because your changes will go to stage automatically and cause errors. And there is the risk someone will deploy them to production.

2024-12-04 18:39 UTC, MichaelRoytman commented on src/data/slice.js
> +  auditTrial: {
Shouldn't the initial state be `{}`? The default would be no trial, which would be represented by the empty object.

2024-12-04 18:39 UTC, MichaelRoytman commented on src/data/thunks.js
> +export function getLearningAssistantSummary(courseId) {
Nit: Could you rename this to `getLearningAssistantChatSummary`? Marcos had some concerns about confusion between that summary and the unit summary, which we may integrate into Learning Assistant.

2024-12-04 18:39 UTC, MichaelRoytman commented on src/data/thunks.js
> +      if (Object.keys(auditTrial).length !== 0) { // eslint-disable-line no-undef
What was the issue with `no-undef` here? I don't see what would be undefined here. Do we need this `eslint-disable` declaration?

2024-12-04 18:39 UTC, MichaelRoytman commented on src/data/thunks.js
> +      if (Object.keys(auditTrial).length !== 0) { // eslint-disable-line no-undef
If `auditTrial` data is empty, is there a reason we shouldn't call `setAuditTrial`. If it's empty, it would just set `auditTrial` to the empty object. Is there something wrong with that behavior? I think that's a reasonable behavior, as the empty object signifies the absence of a trial.

2024-12-04 18:39 UTC, MichaelRoytman commented on src/data/thunks.js
> +      // NOTE: When used to not show if fetching the messages failed
Can you clarify what this comment means? I'm not following.

2024-12-04 18:39 UTC, MichaelRoytman commented on src/widgets/Xpert.jsx
> +// import { getLearningAssistantData } from '../hooks';
Please remove the commented out lines.

2024-12-04 18:39 UTC, MichaelRoytman commented on src/widgets/Xpert.jsx
> +    const auditTrialExpired = (Date.now() - auditTrial.expirationDate) > 0;
`auditTrial.expirationDate` is a string. How is it represented in Redux? If it's just the string representation of the date returned by the backend, which it looks like it is, then it's going to cause a problem. `Date.now() - '2024-12-02T14:59:16.148236Z'`, for example, is going to return `NaN`.

2024-12-04 19:14 UTC, ilee2u commented on src/data/thunks.js
> +      if (Object.keys(auditTrial).length !== 0) { // eslint-disable-line no-undef
Oh that's an artifact from when I was using lodash, I'll get rid of this

2024-12-04 19:15 UTC, ilee2u commented on src/data/thunks.js
> +      // NOTE: When used to not show if fetching the messages failed
I meant to use "we" instead of "when", but also I don't think this comment is necessary so I'm removing it.

2024-12-04 19:17 UTC, ilee2u commented on src/widgets/Xpert.jsx
> +    const auditTrialExpired = (Date.now() - auditTrial.expirationDate) > 0;
Good point, that value is stored in Redux as a string, so I'll create a date object from the string here.

2024-12-04 21:24 UTC, MichaelRoytman approved these changes
Thanks for addressing my feedback.

I left one comment about the conditional used for determining whether a trial has expired, but since the function is not used yet, I'm not blocking merging the PR.

Also, please squash your commits before/when merging.

I'd like to wait for the backend changes to be deployed and tested before we merge this since deployment to stage will be automatic. Could we check in tomorrow about a good time to merge? Thanks.

2024-12-04 21:24 UTC, MichaelRoytman commented on src/widgets/Xpert.jsx
> +    if ((Date.now() - auditTrialExpirationDate) >= 0) {
I think that if the current time is exactly the expiration date (i.e. `Date.now() - auditTrialExpirationDate === 0`), then the trial should be expired, so this should be `>`. What do you think?

2024-12-05 17:07 UTC, merged